from PyQt5 import QtCore , QtGui , QtWidgets  
from PyQt5.QtGui import QPixmap , QIcon
import sys
app = QtWidgets.QApplication(sys.argv)
# app = QtWidgets.QApplication([])
window = QtWidgets.QMainWindow()
window.setWindowTitle('project')
window.resize(600,400)
# input1 = QtWidgets.QLineEdit(window)
# input1.move(80,100)
# input2 = QtWidgets.QComboBox(window)
# input2.addItem('h')
# input2.move(80,130)
# photo = QtWidgets.QLabel(window)
# p = QPixmap('C:\\Users\\Eslam\\Desktop\\p1.jpg').scaled(50,50)
# photo.setPixmap(p)
# msg = QtWidgets.QMessageBox.question(window,'Helloo ','Are U Sure?!')
# photo.resize(p.width(50),p.height(50))
window.move(600,300)
window.setWindowIcon(QtGui.QIcon('C:\\Users\\Eslam\\Desktop\\p1.jpg'))
# bt1 = QtWidgets.QPushButton('btn',window)
#bt1.setToolTip('اسم يظهر علي btn')
# mbar = window.menuBar()
# m1 = mbar.addMenu('file')
# m2 = mbar.addMenu('Edit')
# e1 = QtWidgets.QAction('new',window)
# e2 = QtWidgets.QAction('add',window)
# e3 = QtWidgets.QAction('del',window)
# e4 = QtWidgets.QAction('act',window)
# e5 = QtWidgets.QAction('hh',window)
# m1.addActions([e1,e2])
# i = QtWidgets.QInputDialog.getInt(window,'title','question',10,0,100,1)
window.show()
app.exec_() 